### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Car_Test2Content)
add_subdirectory(Car_Test2)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Car_Test2Contentplugin
    Car_Test2plugin)